# Generated by Django 2.2.4 on 2019-09-05 11:13

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('submitrecipe_app', '0003_auto_20190905_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
