# Generated by Django 2.2.4 on 2019-09-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_auto_20190904_0531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
