# Generated by Django 2.2.4 on 2019-09-05 11:13

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
